server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: opty-socket
  lifecycle:
    timeout-per-shutdown-phase: 10s
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# Opty Socket configuration
opty:
  socket:
    max-connections: ${OPTY_SOCKET_MAX_CONNECTIONS:100}
    cors:
      allowed-origins: ${OPTY_SOCKET_CORS_ALLOWED_ORIGINS:*}
    message:
      max-size: ${OPTY_SOCKET_MESSAGE_MAX_SIZE:65536}
      queue-capacity: ${OPTY_SOCKET_MESSAGE_QUEUE_CAPACITY:100}
    session:
      timeout-minutes: ${OPTY_SOCKET_SESSION_TIMEOUT_MINUTES:30}

# Logging
logging:
  level:
    root: INFO
    com.opty.socket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
